---
title: "Working"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/git/banana-phone/work")
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)

data <- read.csv("surveydata.csv", na = c("#NULL!", ""))
```

# Survey questions
### Q1. Before receiving this survey, did you know influenza is different from the stomach flu?

```{r, echo=TRUE}
# summary
with(data, table(Q1))
q1 <- data %>%
  group_by(Q1) %>%
  count(Q1)

ggplot(q1, aes(x = Q1, y = n, fill = Q1)) +
  geom_bar(stat = 'identity')

# by gender
with(data, table(Q1, PPGENDER))
q1_g <- data %>%
  group_by(Q1, PPGENDER) %>%
  count(Q1, PPGENDER)

ggplot(q1_g, aes(x = Q1, y = n, fill = PPGENDER)) +
  geom_bar(stat = 'identity', position = position_dodge())

```



### Q7. What types of public transportation do you regularly use?

```{r, echo=FALSE}
# summary
Q7 <- data %>%
  select(Q7_1:Q7_otherText) %>%
  rename("Bus" = Q7_1,
         "Carpool" = Q7_2,
         "Subway" = Q7_3,
         "Train" = Q7_4,
         "Taxi" = Q7_5,
         "Airplane" = Q7_6,
         "Other" = Q7_7,
         "Refused" = Q7_8,
         "Other text" = Q7_otherText) %>%
  gather("q", "r", Bus:Other) %>%
  count(q, r)

ggplot(Q7[!is.na(Q7$r), ], aes(x = r, y = n, fill = r)) + geom_bar(stat = 'identity', position = position_dodge()) + facet_wrap(~q)


# by gender
q7_g <- data %>%
  select(PPGENDER, Q7_1:Q7_otherText) %>%
  rename("Bus" = Q7_1,
         "Carpool" = Q7_2,
         "Subway" = Q7_3,
         "Train" = Q7_4,
         "Taxi" = Q7_5,
         "Airplane" = Q7_6,
         "Other" = Q7_7,
         "Refused" = Q7_8,
         "Other text" = Q7_otherText) %>%
  gather("q", "r", Bus:Other) %>%  # exclude Refused and Other text
  group_by(PPGENDER, q, r) %>%
  count(PPGENDER, q, r)

ggplot(q7_g[!is.na(q7_g$r), ], aes(x = r, y = n, fill = PPGENDER)) +
  geom_bar(stat = 'identity', position = position_dodge()) + facet_wrap(~q)

```





